### ISSUE TITLE
Trouble rendering tiles

### ISSUE THREAD

**Issue by D3M05** [thesocialdev/kartodock#2]
Hey, ran across your Docker while trying to figure out vector tile generation from osm data using Kartotherian.  Looks like you've done some great work so far.  I've run through your how to and everything goes ok, but when it comes to launching tilerator and kartotherian I am only getting blank maps on the localhost:16534 and localhost:6533.  I see that you have some todo at the bottom, and was wondering if I needed to do those things manually or if I should be at least getting a map in current form.  Either way, would appreciate any help you can give.  Thanks!

**Comment by D3M05** [comment]
Ok, so I found that the data is indeed getting loaded and is visible when I click set style to genview in tilerator-ui.  I can ctrl-click a tile to render the tiles in that tile, which then show up in Kartotherian at that point.  Just need to figure out how to render an entire area, as the readme at https://github.com/kartotherian/kartotherian/tree/master/packages/tilerator isn't the easiest thing to follow.  Thanks

**Comment by thesocialdev** [comment]
@d3mon187 I appreciate the feedback, please let me know if you have more to add to it.

I intend to improve documentation regarding kartotherian development, but please feel welcome to contribute if you like. Also, is worth to mention that WMF forked kartotherian in order to improve maintainability, see https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/services/kartotherian/

Thanks!

**Comment by D3M05** [comment]
Ah, now it makes sense why you used the mediawiki/services/kartotherian project instead of the original github.  Glad to see there's some recent development work on it.

I'm happy to contribute, which is why it might sound like I'm talking out loud to myself in my posts.  Trying to get a full grasp on all the parts, and then I'll organize all the most obvious things I ran into.  Currently everything seems to be working well enough to get started, which is what I really needed.  Can't thank you enough.  Next steps will be to make sure everything is tweaked to run at full speed for when I crunch the planet.  Appreciate any tips you have to share.  Right now I'm making sure everything is set to use multiple cpu beyond the setting in the env file, including a modified postrgres.conf, and having postgres save data to optane class storage.  Hopefully it won't take as long as it took me to get a full crunch on openmaptiles from like 216 days to 21!

**Comment by D3M05** [comment]
Writing down a few speed bumps I've run into.  Sorry in advanced me just being dumb on some of these.

1.  First had a bit of trouble understanding the folder structure where kartodock is at same level as data, pbf, and the mediawiki kartotherian git clone.  I think I'm just used to having everything inside the main project, so I misunderstood your layout directions.
2.  I needed to add "- PGPASSWORD=secret" to the environment for workspace, otherwise osm import complained about needing a password.
3.  In the config templates, spec was referencing the wrong location and throwing a file not found error.  Might not be a big deal, but changing spec to "spec: /home/kartotherian/packages/kartotherian/spec.template.yaml"  fixed that.

**Comment by D3M05** [comment]
On a separate note, I was wondering if I could pick your brain real quick.  My primary setup consists of tile generator server that renders the planet, which I then push the rendered tiles to two tile servers in a cluster.  Is this possible with Kartotherian?  It's currently looking like I would need to push the entire postgres database and cassandra files over to each tile server.  Is that correct, or am I missing a more portable option?  
Also, where as openmaptiles usually has people rendering to level 18, I noticed that no one is typically rendering past 16 with Kartotherian.  Do you know if this is because Kartotherian is expected to have the ability to render lower zooms on the fly vs OMT needing all zooms pre-rendered, or is there a large difference in processing time/file sizes between the two?

Thanks again!

**Comment by thesocialdev** [comment]
> 1. First had a bit of trouble understanding the folder structure where kartodock is at same level as data, pbf, and the mediawiki kartotherian git clone.  I think I'm just used to having everything inside the main project, so I misunderstood your layout directions.

My intention is to keep it configurable for whatever suits your need, it's worth to mention that kartodock is inspired by [laradock](https://github.com/laradock/laradock). One example of its flexible usage is that sometimes I work with big chunks of planet data and I often choose to store the data folder in an external drive due to limited SSD storage in my personal computer.

Ideally, kartodock will become product-ready so it can be used as a submodule under kartoterian itself or other GIS stack.

> 2. I needed to add "- PGPASSWORD=secret" to the environment for workspace, otherwise osm import complained about needing a password.

Yes, that's right. Sometimes, in the rush of day-to-day work, I just use commands manually and always forget to fix it.

> 3. In the config templates, spec was referencing the wrong location and throwing a file not found error.  Might not be a big deal, but changing spec to "spec: /home/kartotherian/packages/kartotherian/spec.template.yaml"  fixed that.

It is not a big deal for development so it was low priority to me, I'm glad you fixed it!

**Comment by thesocialdev** [comment]
> On a separate note, I was wondering if I could pick your brain real quick. My primary setup consists of tile generator server that renders the planet, which I then push the rendered tiles to two tile servers in a cluster. Is this possible with Kartotherian? It's currently looking like I would need to push the entire postgres database and cassandra files over to each tile server. Is that correct, or am I missing a more portable option?

The current WMF setup uses [8 tile servers across 2 DCs](https://wikitech.wikimedia.org/wiki/Maps#/media/File:Maps-deployment.png). Each DC has a master machine wich will replicate OSM data and generate tiles. Since Tilerator uses service-runner it contains support for multi-dc services, but I'm not sure how this is implemented. For a complete answer, you should ask the creator of the project [Yuri](https://github.com/nyurik).

> Also, where as openmaptiles usually has people rendering to level 18, I noticed that no one is typically rendering past 16 with Kartotherian. Do you know if this is because Kartotherian is expected to have the ability to render lower zooms on the fly vs OMT needing all zooms pre-rendered, or is there a large difference in processing time/file sizes between the two?

Full planet tile generation is not smart in Tilerator yet, so it can take a long time, that's why we don't generate further zooms. We use overzoom to create vector-tiles on demand for those zoom-levels based on the "parent tile" data. Here are some [benchmarks and past work](https://www.mediawiki.org/wiki/Wikimedia_Maps/Tile_generation_report) about this that could be useful.

I hope it's useful.
