### ISSUE TITLE
Missing Buildings

### ISSUE THREAD

**Issue by D3M05** [thesocialdev/kartodock#9]
So this might be an issue with the forked OSM Bright style, but I noticed that certain buildings seem to be missing from the maps.  I couldn't find any documentation, discussion, or a rhyme or reason why.  An example can be seen at https://maps.wikimedia.org/#18/29.48918/-98.44675 vs https://www.openstreetmap.org/#map=18/29.48918/-98.44675 .  You can see that the building with the Target is missing, but other buildings like the Whataburger are there.  I am seeing the same on mine with updated data, and it seems strange that some buildings in this area aren't rendered but other Targets and big shopping areas render fine.  @thesocialdev  could you point me in the right direction on where to fix this?  Also, how hard would it be to add POI labels like Openstreemap?  Thanks!

**Comment by thesocialdev** [comment]
@d3mon187 this is probably related to [T218097](https://phabricator.wikimedia.org/T218097). This led me to several investigations with OSM replication, I even tried to move to imposm3 (still needs tweaking to work with osm-bright), which you can see in [this branch](https://github.com/thesocialdev/kartodock/tree/imposm3). But, if the buildings are not being included in the queries, first you should try to find [the polygon](https://www.openstreetmap.org/way/774903520#map=18/29.48929/-98.44669) in our database, you can check for an osm_id in the `planet_*` tables and audit the osm-bright [layer queries](https://github.com/kartotherian/osm-bright.tm2source/blob/master/data.yml#L206).

I normally do that in kartodock logging in the database through the workspace or postgres-postgis container, something like:
```
docker-compose exec workspace psql -d gis 
```

Regarding POI labels, you can try to use `mapbox-studio-classic` to edit osm-bright project, but it has been a long time since I used it and it's probably not supported properly in the current setup, but that's the easiest way to test new styled layers.

I hope that helps.

**Comment by D3M05** [comment]
Thanks, that definitely gives me something to work with.  I'll see if I can get it working and report back if I find a fix.

**Comment by D3M05** [comment]
Ok, another day, another new thing learned about OSM.

So, the problem is indeed linked to T218097, and I just managed to randomly test an area that was added 2 months ago and now realize that both our data is a bit old now.  lol

I didn't need to mess with any mapbox stuff since your pointing me to the layer queries was enough for me to figure how it all works out.  It is surprisingly simple to work with the styling stuff, and I've already got a lot of POIs added in, as well as some major landuse areas I felt were missing.  Right now I'm just grabbing distinct features with high counts, and manually matching them with the icons already there.  It's a shame that OSM hasn't done a better job keeping the data more uniform for amenities.

I do have one more question for the pile.  If I change the data.yml and osm-bright-style to include POIs, will that be hard coded into the rendered vector styles, or is there an option to exclude them with a different style like you can do with language label changes?

**Comment by D3M05** [comment]
Hey @thesocialdev, long time no bug, haha.  Hope you've been well and keeping safe.

I managed to get my styling done and a system setup processing, rendering, and updating.  Now I feel like I just ran into a big wall that I should have seen coming.  The question is, can I display a vector map without being under the rule of mapbox-gl or openmaptiles' vector styles?

**Comment by D3M05** [comment]
Oh the joys of licensing.  I noticed that the mapbox-gl-style of osm-bright seems to have a similar license to the one forked into Kartotherian?  If they are the same, then do you happen to know why openmaptiles went off and made their own schema when Mapbox told them to not use the streets style?  I don't mind crediting the style for Mapbox on a linked page, but don't want to fall into any legal pitfalls with using their styles or modifying them to include all the features from the non-gl osm-bright.

From my current understanding there are a couple options I've found using a pbf source.

1. Use mapbox-gl with the "open" osm-bright-gl style, and modify it to include street names, pois, and align it with the kartotherian version of osm-bright.

2. Another option would be to use openlayers, and I don't think it would be too difficult to create and adapt a style function to the osm-bright style sort of like was done in this example to the streets style - https://openlayers.org/en/latest/examples/mapbox-vector-tiles-advanced.html

3. It seems like it's possible to also use the osm-bright-gl style with openlayers using https://github.com/openlayers/ol-mapbox-style , but I haven't gotten that method working yet.

Are there any other methods of vector mapping I'm missing?

**Comment by thesocialdev** [comment]
> Oh the joys of licensing. I noticed that the mapbox-gl-style of osm-bright seems to have a similar license to the one forked into Kartotherian? If they are the same, then do you happen to know why openmaptiles went off and made their own schema when Mapbox told them to not use the streets style? I don't mind crediting the style for Mapbox on a linked page, but don't want to fall into any legal pitfalls with using their styles or modifying them to include all the features from the non-gl osm-bright.

This is a long stand issue, see https://github.com/kartotherian/osm-bright.tm2source/issues/45 we do have some concerns about that, but because of the lack of resources, we let it as it is since there aren't many major implications considering that we credit it in our platform. The reason for openmaptiles to move away from the it is unknown to me, but I guess it was also related to the evolution of their platform since mapnik was losing grounds and CartoCSS started its "deprecation" phase.

> 
> From my current understanding there are a couple options I've found using a pbf source.
> 
> 1. Use mapbox-gl with the "open" osm-bright-gl style, and modify it to include street names, pois, and align it with the kartotherian version of osm-bright.
> 2. Another option would be to use openlayers, and I don't think it would be too difficult to create and adapt a style function to the osm-bright style sort of like was done in this example to the streets style - https://openlayers.org/en/latest/examples/mapbox-vector-tiles-advanced.html
> 3. It seems like it's possible to also use the osm-bright-gl style with openlayers using https://github.com/openlayers/ol-mapbox-style , but I haven't gotten that method working yet.
> 
> Are there any other methods of vector mapping I'm missing?

So, I need to take a closer look, but the projects you listed are mapbox-gl based, which is not currently supported by kartotherian. I'll link here a WIP patch that I had to move away from tm2source and start supporting mapbox-gl, see https://github.com/wikimedia/mediawiki-services-kartotherian/pull/4

It's just a scratch of an idea, I never get the chance to finish and make it work.

**Comment by thesocialdev** [comment]
> Ok, another day, another new thing learned about OSM.
> 
> So, the problem is indeed linked to T218097, and I just managed to randomly test an area that was added 2 months ago and now realize that both our data is a bit old now. lol
> 
> I didn't need to mess with any mapbox stuff since your pointing me to the layer queries was enough for me to figure how it all works out. It is surprisingly simple to work with the styling stuff, and I've already got a lot of POIs added in, as well as some major landuse areas I felt were missing. Right now I'm just grabbing distinct features with high counts, and manually matching them with the icons already there. It's a shame that OSM hasn't done a better job keeping the data more uniform for amenities.
> 
> I do have one more question for the pile. If I change the data.yml and osm-bright-style to include POIs, will that be hard coded into the rendered vector styles, or is there an option to exclude them with a different style like you can do with language label changes?

Kartotherian does not have a filtering mechanism in place for vector-tiles rendering if you do client-side rendering maybe you can manipulate it.

**Comment by D3M05** [comment]
This is what I've been spending most of my time on lately.  I'm ultimately hoping to have a vector map that I can integrate into my own products, and also want to build a hosted API for all the other pieces I've built to make my sites work.  I have had my own raster maps for MANY years, and figured vector was a must if I were to open up my APIs to the public.  I'm hoping with the addition of my search and geocoding APIs that maybe I can find a place in the market.  I'm close to finishing my style, and once I finish rendering everything then I promise I'll show it off.  :)

The style I built VERY loosely uses the osm-carto data source ( https://github.com/gravitystorm/openstreetmap-carto ) which is public domain licensed.  I say loosely, because it is 95% original at this point.  My goal for the data side was to bring in as much relevant data at each level as possible without overwhelming the user.

For the style side, I also decided to go the openmaptiles route and did an original design, albeit adapted from the major styles of OSM carto.  I then went level by level and continued the trend of as much data as possible while keeping a calm and neutral look.  Again, most was written from scratch.  The main colors were taken from the OSM carto style, but I reduced the contrast and shifted some colors so that everything sort of blends together and is easy on the eyes.  A lot of the colors are based on their themes (school bus yellow for schools, scrubs blue for hospitals, forest green, etc).  All neutral colors, and no one thing should ever leap off the page at you.  I wrote it as an Openlayers style, so it's fully vector with a matching raster version.  I'm super proud of it, and think it's beautiful.  I have a better respect for Mapbox's decision to protect their OSM-Streets style if it's depth is anything like mine, whereas I feel OSM-bright was absolutely bare bones and largely derivative of OSM.  To be honest, I suppose their use of licenses are appropriate.  At over 1750+ lines of code just for my vector style, it certainly isn't simple!  I'd like to open mine up, but also have to wrestle with keeping it as distinctly my product's style so I can differentiate.  As you're coming from Wikimedia, if you have any recommendations or any information I would love to hear it.  Right now I'm struggling to understand how the GPL GNU v2 license affects my style.  I'm fairly certain that I can require attribution on my styles "look and feel" as Mapbox calls it, but if I released my data source would I be required to release under GNU?  I would think Mapbox's use of a mixture of licenses would say no, and that they are separate and distinct pieces of software, but I figure you probably have more experience with this than me.

Thanks again and stay safe!

**Comment by wikiocity** [comment]
Hey @thesocialdev , just wanted to share the new map system.  It's been a crazy year developing everything, but I finally have something I can show off.  That's not to say I don't still have a ton of work to do!  Still very much in beta.  

I have released my openlayers style on github, and will hopefully open up everything as time progresses.  I figure I can always go more open on the license, but it's hard to go back.  I figured out because my style is portable between programs, it is not bound by the GNU.  So releasing the datasource in the future is a possibility.  I did however try to keep the schema as close to OSM Carto as possible, so it wouldn't be difficult to adapt their datasource to my style, and I may even do that myself and release it as public domain.  I still need to port my style to mapbox gl, but for now the Openlayers does work for vector even if it isn't as smooth as I'd like.  So anyways, go easy on me.  This was months of pouring through OSM docs, and tweaking queries down to the ms.

You can check out the map at https://api.wikiocity.com/map
github style is at https://github.com/wikiocity/wikiocity-styles

Thanks for all the help!

**Comment by thesocialdev** [comment]
@wikiocity that's awesome work! Really good indeed. I'm happy to see it becoming reality.

You're right, licensing is tricky and not easy to handle. If you ever release the data source please let me know 😄
